image_publish_topic: 'image_raw'
resend_timer_duration: 2  # seconds

balls_topic: 'balls_in_image'
obstacles_topic: 'obstacles_in_image'
lines_topic: 'lines_in_image'
goalposts_topic: 'balls_in_image'
